#!/usr/bin/env node
// Stamps the shared header, mobile menu, footer and tools lists into every
// HTML page, and regenerates sitemap.xml. Pages stay plain static HTML, so the
// Hostinger deploy is unchanged; this script only rewrites marked regions.
//
//   node scripts/build-site.mjs          rewrite files in place
//   node scripts/build-site.mjs --check  exit 1 if any file is out of date
//
// No dependencies. Source data lives in scripts/site-data.mjs.

import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { join, relative, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import { SITE_ORIGIN, NAV_LINKS, CTA, FOOTER_LINKS, TOOLS, TOOLS_HUB, toolPath } from './site-data.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');
const SKIP_DIRS = new Set(['.git', 'node_modules', 'scripts', 'images', 'assets']);

const NOTE = 'generated by scripts/build-site.mjs from scripts/site-data.mjs, edit those instead';

export function listHtmlFiles(dir = ROOT) {
  const out = [];
  for (const name of readdirSync(dir)) {
    if (name.startsWith('.') || SKIP_DIRS.has(name)) continue;
    const full = join(dir, name);
    if (statSync(full).isDirectory()) out.push(...listHtmlFiles(full));
    else if (name.endsWith('.html')) out.push(full);
  }
  return out.sort();
}

function canonicalOf(html) {
  const m = html.match(/<link\s+rel="canonical"\s+href="([^"]+)"/i);
  return m ? m[1] : null;
}

function pagePath(html, file) {
  const canonical = canonicalOf(html);
  if (canonical) return new URL(canonical).pathname;
  let p = '/' + relative(ROOT, file).replace(/\\/g, '/').replace(/\.html$/, '');
  if (p.endsWith('/index')) p = p.slice(0, -5);
  return p;
}

const esc = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

function linkAttrs(link, path) {
  if (link.external) return ` target="_blank" rel="noopener"`;
  if (!link.match || !link.match(path)) return '';
  return link.href === path ? ` class="active" aria-current="page"` : ` class="active"`;
}

function renderNav(path) {
  const items = NAV_LINKS.map((l) => `    <li><a href="${l.href}"${linkAttrs(l, path)}>${esc(l.label)}</a></li>`).join('\n');
  const mobile = [...NAV_LINKS, CTA].map((l) => `  <a href="${l.href}"${linkAttrs(l, path)}>${esc(l.label)}</a>`).join('\n');
  return `<!-- site:nav (${NOTE}) -->
<nav id="nav" aria-label="Main">
  <a href="/" class="nav-logo" aria-label="Harp Chatha Search home">
    <span class="nav-logo-top">Harp Chatha</span>
    <span class="nav-logo-bottom">Search</span>
  </a>
  <ul class="nav-links">
${items}
  </ul>
  <a href="${CTA.href}" class="nav-cta">${esc(CTA.label)} &rarr;</a>
  <button class="hamburger" id="hamburger" type="button" aria-label="Open menu" aria-expanded="false" aria-controls="mobile-menu"><span></span><span></span><span></span></button>
</nav>
<div class="mobile-menu" id="mobile-menu">
${mobile}
</div>
<!-- /site:nav -->`;
}

function renderFooter(path) {
  const items = FOOTER_LINKS.map((l) => `    <li><a href="${l.href}"${linkAttrs(l, path)}>${esc(l.label)}</a></li>`).join('\n');
  return `<!-- site:footer (${NOTE}) -->
<footer class="site-footer">
  <a href="/" class="footer-logo" aria-label="Harp Chatha Search home">
    <span class="footer-logo-top">Harp Chatha</span>
    <span class="footer-logo-bottom">Search</span>
  </a>
  <ul class="footer-links" aria-label="Footer">
${items}
  </ul>
  <div class="footer-copy">&copy; 2026 Harpreet Singh Chatha</div>
</footer>
<!-- /site:footer -->`;
}

function renderCards(tools, headingTag) {
  return `<ul class="tool-grid">
${tools.map((t) => `  <li><a class="tool-card" href="${toolPath(t)}"><${headingTag}>${esc(t.name)}</${headingTag}><p>${esc(t.description)}</p><span class="try" aria-hidden="true">Try it &rarr;</span></a></li>`).join('\n')}
</ul>`;
}

function renderHub() {
  return `<!-- tools:hub (${NOTE}) -->
${renderCards(TOOLS, 'h2')}
<!-- /tools:hub -->`;
}

function renderMore(currentSlug) {
  const others = TOOLS.filter((t) => t.slug !== currentSlug);
  return `<!-- tools:more slug="${currentSlug}" (${NOTE}) -->
<section class="more-tools" aria-labelledby="more-tools-heading">
  <h2 id="more-tools-heading">More free tools</h2>
${renderCards(others, 'h3')}
</section>
<!-- /tools:more -->`;
}

const HAMBURGER_INLINE = /\n?[ \t]*const hamburger = document\.getElementById\('hamburger'\);[\s\S]*?mobileMenu\.classList\.remove\('open'\);\s*\}\)\);/;

function transform(html, file) {
  const path = pagePath(html, file);
  let out = html;

  // Header and mobile menu: replace a previous stamp, or the original hand written markup.
  const navStamp = /<!-- site:nav[\s\S]*?<!-- \/site:nav -->/;
  if (navStamp.test(out)) out = out.replace(navStamp, () => renderNav(path));
  else {
    const legacy = /<nav id="nav"[^>]*>[\s\S]*?<\/nav>(\s*<div class="mobile-menu" id="mobile-menu">[\s\S]*?<\/div>)?/;
    if (!legacy.test(out)) throw new Error(`${relative(ROOT, file)}: no <nav id="nav"> found`);
    out = out.replace(legacy, () => renderNav(path));
  }

  const footStamp = /<!-- site:footer[\s\S]*?<!-- \/site:footer -->/;
  if (footStamp.test(out)) out = out.replace(footStamp, () => renderFooter(path));
  else {
    const legacy = /<footer[^>]*>[\s\S]*?<\/footer>/;
    if (!legacy.test(out)) throw new Error(`${relative(ROOT, file)}: no <footer> found`);
    out = out.replace(legacy, () => renderFooter(path));
  }

  out = out.replace(/<!-- tools:hub[\s\S]*?<!-- \/tools:hub -->/, () => renderHub());
  out = out.replace(/<!-- tools:more slug="([^"]+)"[\s\S]*?<!-- \/tools:more -->/, (_, slug) => {
    if (!TOOLS.some((t) => t.slug === slug)) throw new Error(`${relative(ROOT, file)}: unknown tool slug ${slug}`);
    return renderMore(slug);
  });

  // The shared script now owns the mobile menu, so drop the per page copy.
  out = out.replace(HAMBURGER_INLINE, '');

  if (!out.includes('href="/assets/site.css"')) {
    out = out.replace('</head>', '  <link rel="stylesheet" href="/assets/site.css" />\n</head>');
  }
  if (!out.includes('src="/assets/site.js"')) {
    out = out.replace('</body>', '<script src="/assets/site.js" defer></script>\n</body>');
  }
  return { out, path };
}

function lastmod(file) {
  try {
    const status = execFileSync('git', ['status', '--porcelain', '--', file], { cwd: ROOT }).toString().trim();
    if (!status) {
      const d = execFileSync('git', ['log', '-1', '--format=%cs', '--', file], { cwd: ROOT }).toString().trim();
      if (d) return d;
    }
  } catch { /* not a git checkout */ }
  return new Date().toISOString().slice(0, 10);
}

function buildSitemap(pages) {
  const urls = pages
    .filter((p) => p.canonical && !/<meta\s+name="robots"\s+content="[^"]*noindex/i.test(p.html))
    .sort((a, b) => a.canonical.localeCompare(b.canonical))
    .map((p) => `  <url>\n    <loc>${p.canonical}</loc>\n    <lastmod>${p.lastmod}</lastmod>\n  </url>`);
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.join('\n')}\n</urlset>\n`;
}

function main() {
  const stale = [];
  const pages = [];
  for (const file of listHtmlFiles()) {
    const html = readFileSync(file, 'utf8');
    const { out } = transform(html, file);
    const canonical = canonicalOf(out);
    if (canonical && !canonical.startsWith(SITE_ORIGIN + '/')) {
      throw new Error(`${relative(ROOT, file)}: canonical ${canonical} is not on ${SITE_ORIGIN}`);
    }
    if (out !== html) {
      stale.push(relative(ROOT, file));
      if (!CHECK) writeFileSync(file, out);
    }
    pages.push({ file, html: out, canonical, lastmod: out !== html ? new Date().toISOString().slice(0, 10) : lastmod(file) });
  }

  const sitemapFile = join(ROOT, 'sitemap.xml');
  const sitemap = buildSitemap(pages);
  const oldSitemap = existsSync(sitemapFile) ? readFileSync(sitemapFile, 'utf8') : '';
  // Ignore lastmod churn when checking, only the URL set matters.
  const locs = (s) => (s.match(/<loc>[^<]+<\/loc>/g) || []).join('\n');
  if (locs(sitemap) !== locs(oldSitemap) || (!CHECK && sitemap !== oldSitemap)) {
    if (locs(sitemap) !== locs(oldSitemap)) stale.push('sitemap.xml');
    if (!CHECK) writeFileSync(sitemapFile, sitemap);
  }

  if (CHECK) {
    if (stale.length) {
      console.error('Out of date, run `npm run build`:\n  ' + stale.join('\n  '));
      process.exit(1);
    }
    console.log(`All ${pages.length} pages and sitemap.xml are up to date.`);
  } else {
    console.log(stale.length ? 'Updated:\n  ' + stale.join('\n  ') : 'Nothing to update.');
    console.log(`sitemap.xml lists ${(sitemap.match(/<loc>/g) || []).length} URLs.`);
  }
}

main();
